shinyUI(
    fluidPage(
        list(tags$head(HTML('<link rel="icon", href="MyIcon.png", 
                                   type="image/png" />')),
             tags$style(HTML('.navbar{
background-color:#212121;
}
         skin-blue .main-sidebar .sidebar .sidebar-menu .active a{
                              background-color: #ff0000;
                              }
'))),
        div(style="padding: -10px 10px; width: '100%'",
            titlePanel(
                title="", windowTitle="Data Sets"
            )
            ),
navbarPage(title=div(img(src="gobmxlogo.svg"), "    "),
           position = "fixed-top",
                   theme="http://framework-gb.cdn.gob.mx/assets/styles/main.css",
                   tabPanel("Instituciones",
                            fluidRow(
                                column(4, wellPanel(
                                              selectInput("inst", "Institución",
                                                          c("SFP",
"Procuraduría Agraria",
"ELCCC",
"Telecomm",
"SE",
"ProMéxico",
"SEDESOL",
"IPN",
"COFAA",
"FIRCO",
"COFAA",
"CONASAMI",
"CIO",
"SEGOB",
"CAPUFE",
"ISSSTE",
"Seguro Popular",
"Notimex",
"CONALITEG",
"Notimex",
"CONALEP",
"Notimex",
"CONAPESCA",
"CONACYT",
"SAT",
"CONSAR",
"FIFONAFE",
"CNSF",
"IPAB",
"API-DB",
"SE",
"INAH",
"AGROASEMEX",
"CONAGUA",
"CIMAT",
"FOCIR",
"CONABIO",
"PRODECON",
"CICESE",
"SEDENA",
"Instituto Mora",
"BANCOMEXT",
"SESNSP",
"Secretaría de Energía",
"CINETECA NACIONAL",
"CONDUSEF",
"CRAE",
"PEMEX",
"CRE",
"COLPOS",
"PRONABIVE",
"SEDESOL",
"FONART",
"CONANP",
"IIE",
"SFP",
"PGR",
"SHF",
"AICM",
"INAPAM",
"PGR",
"INALI",
"BIRMEX",
"Centro de Investigaciones y Estudios Superiores en Antropología Social",
"COLSAN",
"API-MTT",
"SNICS",
"CONOCER",
"INECC",
"CONAPRED",
"API-GYM",
"API-SCX",
"CIBNOR",
"CONAFOR",
"SFP",
"Presidencia",
"SAE",
"API-LZC",
"HRAEB",
"Telecomm",
"INIFED",
"DICONSA",
"API-VSA",
"Canal 11",
"API-ATM",
"HGGEA",
"COLEF",
"CIDETEQ",
"API-TAM",
"SENASICA",
"HRAEB",
"IMTA",
"IMP",
"Veracruz Municipio",
"INC",
"Veracruz",
"INIFED",
"IIE",
"CMM",
"BANJERCITO",
"PROFEDET",
"Secretaría de Energía",
"INFOTEC",
"Ciudad Juárez",
"PROFEDET",
"Sistema Público de Radiofusión del Estado Mexicano",
"FIRA",
"API-ESE",
"Puebla",
"Procuraduría Federal de Protección al Ambiente",
"CFE",
"PEMEX",
"Ayuntamiento de Xalapa",
"Aeropuertos y Servicios Auxiliares",
"SEDESOL",
"imt",
"SNDIF",
"INMUJERES",
"SAGARPA",
"Ayuntamiento de Zapopan",
"PEMEX",
"SHCP",
"Correos de México",
"SALUD",
"INEGI",
"NAFIN",
"INEGI",
"SCT",
"CONEVAL",
"CFE",
"Presidencia",
"SEDESOL",
"SEDATU",
"SEP",
"INMUJERES",
"Fondo de Cultura Económica",
"Servicio Geológico Mexicano",
"SECTUR",
"STPS",
"CONAPO",
"Ayuntamiento de San Luis Potosí",
"Secretaría de Energía",
"IMSS",
"Instituto del Fondo Nacional para el Consumo de los Trabajadores",
"SEMARNAT",
"Servicio Geológico Mexicano",
"SAGARPA",
"ift",
"SE",
"IEPSA",
"Ayuntamiento de Zapopan",
"CENAPRED",
"SAGARPA",
"ProMéxico",
"RAN",
"CDI",
"Estado de Morelos",
"Estado de Jalisco",
"Estado de Puebla",
"RAN",
"Ayuntamiento de San Pedro Garza García",
"SE"),
                                                          selected = "SEP"
                                                          )
)),
column(8, img(src="bck_pres.jpg",height=180)),
column(12, wellPanel(
      # This outputs the dynamic UI component
      uiOutput("ui")
    ))
  )))
))

