shinyUI(
    fluidPage(
        navbarPage(title= "Escuadrón de Datos",#div(img(src="logomxa.png",style="width:100px;height:100px"), "    "),
        ##   position = "fixed-top",
                   theme="http://bootswatch.com/readable/bootstrap.min.css",
                   tabPanel("Dashboard",
                            fluidRow(
                                column(3, wellPanel(
                                              selectInput("inst", "Dependencia",
                                                          c("General",
                                                            "SFP",
                                                            "Procuraduría Agraria",
                                                            "ELCCC",
                                                            "Telecomm",
                                                            "SE",
                                                            "ProMéxico",
                                                            "SEDESOL",
                                                            "IPN",
                                                            "COFAA",
                                                            "FIRCO",
                                                            "COFAA",
                                                            "CONASAMI",
                                                            "CIO",
                                                            "SEGOB",
                                                            "CAPUFE",
                                                            "ISSSTE",
                                                            "Seguro Popular",
                                                            "Notimex",
                                                            "CONALITEG",
                                                            "Notimex",
                                                            "CONALEP",
                                                            "Notimex",
                                                            "CONAPESCA",
                                                            "CONACYT",
                                                            "SAT",
                                                            "CONSAR",
                                                            "FIFONAFE",
                                                            "CNSF",
                                                            "IPAB",
                                                            "API-DB",
                                                            "SE",
                                                            "INAH",
                                                            "AGROASEMEX",
                                                            "CONAGUA",
                                                            "CIMAT",
                                                            "FOCIR",
                                                            "CONABIO",
                                                            "PRODECON",
                                                            "CICESE",
                                                            "SEDENA",
                                                            "Instituto Mora",
                                                            "BANCOMEXT",
                                                            "SESNSP",
                                                            "Secretaría de Energía",
                                                            "CINETECA NACIONAL",
                                                            "CONDUSEF",
                                                            "CRAE",
                                                            "PEMEX",
                                                            "CRE",
                                                            "COLPOS",
                                                            "PRONABIVE",
                                                            "SEDESOL",
                                                            "FONART",
                                                            "CONANP",
                                                            "IIE",
                                                            "SFP",
                                                            "PGR",
                                                            "SHF",
                                                            "AICM",
                                                            "INAPAM",
                                                            "PGR",
                                                            "INALI",
                                                            "BIRMEX",
                                                            "Centro de Investigaciones y Estudios Superiores en Antropología Social",
                                                            "COLSAN",
                                                            "API-MTT",
                                                            "SNICS",
                                                            "CONOCER",
                                                            "INECC",
                                                            "CONAPRED",
                                                            "API-GYM",
                                                            "API-SCX",
                                                            "CIBNOR",
                                                            "CONAFOR",
                                                            "SFP",
                                                            "Presidencia",
                                                            "SAE",
                                                            "API-LZC",
                                                            "HRAEB",
                                                            "Telecomm",
                                                            "INIFED",
                                                            "DICONSA",
                                                            "API-VSA",
                                                            "Canal 11",
                                                            "API-ATM",
                                                            "HGGEA",
                                                            "COLEF",
                                                            "CIDETEQ",
                                                            "API-TAM",
                                                            "SENASICA",
                                                            "HRAEB",
                                                            "IMTA",
                                                            "IMP",
                                                            "Veracruz Municipio",
                                                            "INC",
                                                            "Veracruz",
                                                            "INIFED",
                                                            "IIE",
                                                            "CMM",
                                                            "BANJERCITO",
                                                            "PROFEDET",
                                                            "Secretaría de Energía",
                                                            "INFOTEC",
                                                            "Ciudad Juárez",
                                                            "PROFEDET",
                                                            "Sistema Público de Radiofusión del Estado Mexicano",
                                                            "FIRA",
                                                            "API-ESE",
                                                            "Puebla",
                                                            "Procuraduría Federal de Protección al Ambiente",
                                                            "CFE",
                                                            "PEMEX",
                                                            "Ayuntamiento de Xalapa",
                                                            "Aeropuertos y Servicios Auxiliares",
                                                            "SEDESOL",
                                                            "imt",
                                                            "SNDIF",
                                                            "INMUJERES",
                                                            "SAGARPA",
                                                            "Ayuntamiento de Zapopan",
                                                            "PEMEX",
                                                            "SHCP",
                                                            "Correos de México",
                                                            "SALUD",
                                                            "INEGI",
                                                            "NAFIN",
                                                            "INEGI",
                                                            "SCT",
                                                            "CONEVAL",
                                                            "CFE",
                                                            "Presidencia",
                                                            "SEDESOL",
                                                            "SEDATU",
                                                            "SEP",
                                                            "INMUJERES",
                                                            "Fondo de Cultura Económica",
                                                            "Servicio Geológico Mexicano",
                                                            "SECTUR",
                                                            "STPS",
                                                            "CONAPO",
                                                            "Ayuntamiento de San Luis Potosí",
                                                            "Secretaría de Energía",
                                                            "IMSS",
                                                            "Instituto del Fondo Nacional para el Consumo de los Trabajadores",
                                                            "SEMARNAT",
                                                            "Servicio Geológico Mexicano",
                                                            "SAGARPA",
                                                            "ift",
                                                            "SE",
                                                            "IEPSA",
                                                            "Ayuntamiento de Zapopan",
                                                            "CENAPRED",
                                                            "SAGARPA",
                                                            "ProMéxico",
                                                            "RAN",
                                                            "CDI",
                                                            "Estado de Morelos",
                                                            "Estado de Jalisco",
                                                            "Estado de Puebla",
                                                            "RAN",
                                                            "Ayuntamiento de San Pedro Garza García",
                                                            "SE"),
                                                          selected = "General"
                                                          )
                                          )),
                                column(3,
                                       column(12,
                                              box(width = 12, status = "info",
                                                  title = "Dependencias",
                                                  div(infoBoxOutput("dep"),
                                                      style="width: 40% ; height: 60px ; margin: 10px 10px 10px 10px ;float:left ")))
                                       ),
                                column(3,
                                       column(12,
                                              h2("Conjuntos", style="color:#2196F3")
                                              ),
                                       column(12, offset=2,
                                              h2(textOutput("set"), style="color:#2196F3")
                                              )
                                       ),
                                column(3,
                                       column(12,
                                              h2("Recursos", style="color:#2196F3")
                                              ),
                                       column(12,offset=2,
                                              h2(textOutput("rec"), style="color:#2196F3")
                                              )
                                       ),
                                column(12, hr()),
                                column(12, wellPanel(
                                        # This outputs the dynamic UI component
                                               plotlyOutput("openhist")   #, height = 2500),
                                           ))
                            )),
                   tabPanel("Reporte"),
                   tabPanel("Contacto")
                   )
    ))

